language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
  - openjdk7

before_install:
  - mvn install -DskipTests=true -DfinalName=helloci
  - pip install --user codecov

install:
  - mvn clean install test
after_success:
  - codecov
  - coveralls
